### PR TITLE
Add busy indicator until ready

### PR DESCRIPTION
**Pull request by nephros**

### CODE REVIEW

**Comment by b100dian** [comment]
Not sure if this is needed, there's an equivalent loading inside the webview..

**Comment by pherjung** [comment]
> Not sure if this is needed, there's an equivalent loading inside the webview..

I agree, perhaps it would make more sense to move this feature to the cover page.

**Review by b100dian — APPROVED** [review]
Ok, I guess the message could be tweaked though. Like "Starting Hydrogen" or even "Catalyzing Hydrogen" or "Hydrolyzing" if you want to be reticulating-splines funny:)

**Comment by b100dian** [comment]
> Like this? :)

I love it!

**Pull request merged**
